import Navbar from "@/components/navbar";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";

const instrumentalSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrumental-sans",
});

export const metadata: Metadata = {
  title: "IIMSC - Hiring Made Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentalSans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
